# Daily retrieve EUR/CHF exchange data from ECB
name: jobs.ch watcher

# Controls when the action will run.
on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches: main

jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages(c("rvest", "readr", "stringr", "tibble", "writexl"))'
    # Run R script
    - name: Scrape jobs.ch
      run: Rscript scraper_jobs_ch.R
      
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add -A
        git commit -am "Data retrieved - $(date)" || echo "No changes to commit"
        git push origin main || echo "No changes to commit"
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
